services:
  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    image: nginx:1.26.0-alpine3.19
    environment:
      DOMAIN_NAME: '${DOMAIN_NAME}'
    ports:
      - '${NGINX_HTTP_PORT}:80'
      - '${NGINX_HTTPS_PORT}:443'
    volumes:
      - type: bind
        source: ./docker/nginx/templates
        target: /etc/nginx/templates
      - type: bind
        source: ./docker/nginx/certs
        target: /etc/nginx/certs
      - type: bind
        source: ./src
        target: /var/www/src
    working_dir: /var/www/src
    networks:
      - backend-network
  php:
    container_name: ${COMPOSE_PROJECT_NAME}_php
    build:
      context: ./docker/php
    image: ${COMPOSE_PROJECT_NAME}_php
    environment:
      PHP_XDEBUG_ENABLE: ${PHP_XDEBUG_ENABLE}
      PHP_IDE_CONFIG: 'serverName=${IDE_CONFIG_SERVER_NAME}'
    volumes:
      - type: bind
        source: ./src
        target: /var/www/src
    working_dir: /var/www/src
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge